# Data analysis with python .

*After we have collected data from different sources we can analyse our data,deal with the missing values by replacing it with mean or mode or any other methods or drop the missing value,do the data formating,correcting the datatypes etc.Below I have taken some examples on how to do analysis of the collected data and drop the missing values in our dataframe.*

### import pandas to the jupyter notebook

In [14]:
import pandas as pd

### create data frame by a sample data sets .

In [15]:
df=pd.read_csv('https://data.cityofchicago.org/resource/jcxq-k9xf.csv')

### display the first 5 rows of the data frame to check wheter the values are added properly or not.

In [16]:
df.head()

,ca,community_area_name,percent_of_housing_crowded,percent_households_below_poverty,percent_aged_16_unemployed,percent_aged_25_without_high_school_diploma,percent_aged_under_18_or_over_64,per_capita_income_,hardship_index
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0

### use datafram.dtypes to know the datatypes of the columns.

In [20]:
df.dtypes

ca                                             float64
community_area_name                             object
percent_of_housing_crowded                     float64
percent_households_below_poverty               float64
percent_aged_16_unemployed                     float64
percent_aged_25_without_high_school_diploma    float64
percent_aged_under_18_or_over_64               float64
per_capita_income_                               int64
hardship_index                                 float64
dtype: object

### use dataframe.describe(include='all') to know the statistical summary of each column .

In [23]:
df.describe(include='all')

,ca,community_area_name,percent_of_housing_crowded,percent_households_below_poverty,percent_aged_16_unemployed,percent_aged_25_without_high_school_diploma,percent_aged_under_18_or_over_64,per_capita_income_,hardship_index
count,77.000000,78,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,77.000000
unique,NaN,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Belmont Cragin,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,39.000000,NaN,4.920513,21.739744,15.341026,20.330769,35.717949,25597.000000,49.506494
std,22.371857,NaN,3.658981,11.457231,7.499497,11.746514,7.284421,15196.405541,28.690556
min,1.000000,NaN,0.300000,3.300000,4.700000,2.500000,13.500000,8201.000000,1.000000
25%,20.000000,NaN,2.325000,13.350000,9.200000,12.075000,32.150000,15804.750000,25.000000
50%,39.000000,NaN,3.850000,19.050000,13.850000,18.650000,38.050000,21668.500000,50.000000
75%,58.000000,NaN,6.800000,29.150000,20.000000,26.600000,40.500000,28715.750000,74.000000
max,77.000000,NaN,15.800000,56.500000,35.900000,54.800000,51.500000,88669.000000,98.000000

### use dataframe.info to diplay the concise summary of the columns .

In [26]:
df.info

<bound method DataFrame.info of       ca     community_area_name  percent_of_housing_crowded  \
0    1.0             Rogers Park                         7.7
1    2.0              West Ridge                         7.8
2    3.0                  Uptown                         3.8
3    4.0          Lincoln Square                         3.4
4    5.0            North Center                         0.3
5    6.0               Lake View                         1.1
6    7.0            Lincoln Park                         0.8
7    8.0         Near North Side                         1.9
8    9.0             Edison Park                         1.1
9   10.0            Norwood Park                         2.0
10  11.0          Jefferson Park                         2.7
11  12.0             Forest Glen                         1.1
12  13.0              North Park                         3.9
13  14.0             Albany Park                        11.3
14  15.0            Portage Park                         4.1
15  16.0             Irving Park                         6.3
16  17.0                 Dunning                         5.2
17  18.0              Montclaire                         8.1
18  19.0          Belmont Cragin                        10.8
19  20.0                 Hermosa                         6.9
20  21.0                Avondale                         6.0
21  22.0            Logan Square                         3.2
22  23.0           Humboldt park                        14.8
23  24.0               West Town                         2.3
24  25.0                  Austin                         6.3
25  26.0      West Garfield Park                         9.4
26  27.0      East Garfield Park                         8.2
27  28.0          Near West Side                         3.8
28  29.0          North Lawndale                         7.4
29  30.0          South Lawndale                        15.2
..   ...                     ...                         ...
48  49.0                Roseland                         2.5
49  50.0                 Pullman                         1.5
50  51.0           South Deering                         4.0
51  52.0               East Side                         6.8
52  53.0            West Pullman                         3.3
53  54.0               Riverdale                         5.8
54  55.0               Hegewisch                         3.3
55  56.0          Garfield Ridge                         2.6
56  57.0          Archer Heights                         8.5
57  58.0           Brighton Park                        14.4
58  59.0           McKinley Park                         7.2
59  60.0              Bridgeport                         4.5
60  61.0                New City                        11.9
61  62.0             West Elsdon                        11.1
62  63.0               Gage Park                        15.8
63  64.0                Clearing                         2.7
64  65.0               West Lawn                         5.8
65  66.0            Chicago Lawn                         7.6
66  67.0          West Englewood                         4.8
67  68.0               Englewood                         3.8
68  69.0  Greater Grand Crossing                         3.6
69  70.0                 Ashburn                         4.0
70  71.0          Auburn Gresham                         4.0
71  72.0                 Beverly                         0.9
72  73.0       Washington Height                         1.1
73  74.0         Mount Greenwood                         1.0
74  75.0             Morgan Park                         0.8
75  76.0                  O'Hare                         3.6
76  77.0               Edgewater                         4.1
77   NaN                 CHICAGO                         4.7

    percent_households_below_poverty  percent_aged_16_unemployed  \
0                               23.6                         8.7
1                               17.2                         8.8
2                               24.0                         8.9
3                               10.9                         8.2
4                                7.5                         5.2
5                               11.4                         4.7
6                               12.3                         5.1
7                               12.9                         7.0
8                                3.3                         6.5
9                                5.4                         9.0
10                               8.6                        12.4
11                               7.5                         6.8
12                              13.2                         9.9
13                              19.2                        10.0
14                              11.6                        12.6
15                              13.1                        10.0
16                              10.6                        10.0
17                              15.3                        13.8
18                              18.7                        14.6
19                              20.5                        13.1
20                              15.3                         9.2
21                              16.8                         8.2
22                              33.9                        17.3
23                              14.7                         6.6
24                              28.6                        22.6
25                              41.7                        25.8
26                              42.4                        19.6
27                              20.6                        10.7
28                              43.1                        21.2
29                              30.7                        15.8
..                               ...                         ...
48                              19.8                        20.3
49                              21.6                        22.8
50                              29.2                        16.3
51                              19.2                        12.1
52                              25.9                        19.4
53                              56.5                        34.6
54                              17.1                         9.6
55                               8.8                        11.3
56                              14.1                        16.5
57                              23.6                        13.9
58                              18.7                        13.4
59                              18.9                        13.7
60                              29.0                        23.0
61                              15.6                        16.7
62                              23.4                        18.2
63                               8.9                         9.5
64                              14.9                         9.6
65                              27.9                        17.1
66                              34.4                        35.9
67                              46.6                        28.0
68                              29.6                        23.0
69                              10.4                        11.7
70                              27.6                        28.3
71                               5.1                         8.0
72                              16.9                        20.8
73                               3.4                         8.7
74                              13.2                        15.0
75                              15.4                         7.1
76                              18.2                         9.2
77                              19.7                        12.9

    percent_aged_25_without_high_school_diploma  \
0                                          18.2
1                                          20.8
2                                          11.8
3                                          13.4
4                                           4.5
5                                           2.6
6                                           3.6
7                                           2.5
8                                           7.4
9                                          11.5
10                                         13.4
11                                          4.9
12                                         14.4
13                                         32.9
14                                         19.3
15                                         22.4
16                                         16.2
17                                         23.5
18                                         37.3
19                                         41.6
20                                         24.7
21                                         14.8
22                                         35.4
23                                         12.9
24                                         24.4
25                                         24.5
26                                         21.3
27                                          9.6
28                                         27.6
29                                         54.8
..                                          ...
48                                         16.9
49                                         13.1
50                                         21.0
51                                         31.9
52                                         20.5
53                                         27.5
54                                         19.2
55                                         19.3
56                                         35.9
57                                         45.1
58                                         32.9
59                                         22.2
60                                         41.5
61                                         37.0
62                                         51.5
63                                         18.8
64                                         33.6
65                                         31.2
66                                         26.3
67                                         28.5
68                                         16.5
69                                         17.7
70                                         18.5
71                                          3.7
72                                         13.7
73                                          4.3
74                                         10.8
75                                         10.9
76                                          9.7
77                                         19.5

    percent_aged_under_18_or_over_64  per_capita_income_  hardship_index
0                               27.5               23939            39.0
1                               38.5               23040            46.0
2                               22.2               35787            20.0
3                               25.5               37524            17.0
4                               26.2               57123             6.0
5                               17.0               60058             5.0
6                               21.5               71551             2.0
7                               22.6               88669             1.0
8                               35.3               40959             8.0
9                               39.5               32875            21.0
10                              35.5               27751            25.0
11                              40.5               44164            11.0
12                              39.0               26576            33.0
13                              32.0               21323            53.0
14                              34.0               24336            35.0
15                              31.6               27249            34.0
16                              33.6               26282            28.0
17                              38.6               22014            50.0
18                              37.3               15461            70.0
19                              36.4               15089            71.0
20                              31.0               20039            42.0
21                              26.2               31908            23.0
22                              38.0               13781            85.0
23                              21.7               43198            10.0
24                              37.9               15957            73.0
25                              43.6               10934            92.0
26                              43.2               12961            83.0
27                              22.2               44689            15.0
28                              42.7               12034            87.0
29                              33.8               10402            96.0
..                               ...                 ...             ...
48                              41.2               17949            52.0
49                              38.6               20588            51.0
50                              39.5               14685            65.0
51                              42.8               17104            64.0
52                              42.1               16563            62.0
53                              51.5                8201            98.0
54                              42.9               22677            44.0
55                              38.1               26353            32.0
56                              39.2               16134            67.0
57                              39.3               13089            84.0
58                              35.6               16954            61.0
59                              31.3               22694            43.0
60                              38.9               12765            91.0
61                              37.7               15754            69.0
62                              38.8               12171            93.0
63                              37.6               25113            29.0
64                              39.6               16907            56.0
65                              40.6               13231            80.0
66                              40.7               11317            89.0
67                              42.5               11888            94.0
68                              41.0               17285            66.0
69                              36.9               23482            37.0
70                              41.9               15528            74.0
71                              40.5               39523            12.0
72                              42.6               19713            48.0
73                              36.8               34381            16.0
74                              40.3               27149            30.0
75                              30.3               25828            24.0
76                              23.8               33385            19.0
77                              33.5               28202             NaN

[78 rows x 9 columns]>

### drop the missing values in the dataframe by dataframe.dropna(subset["column-name"],axis=0)---To delete rows having column value=0.

In [32]:
df.dropna(subset=["community_area_name"],axis=0)

,ca,community_area_name,percent_of_housing_crowded,percent_households_below_poverty,percent_aged_16_unemployed,percent_aged_25_without_high_school_diploma,percent_aged_under_18_or_over_64,per_capita_income_,hardship_index
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0
5,6.0,Lake View,1.1,11.4,4.7,2.6,17.0,60058,5.0
6,7.0,Lincoln Park,0.8,12.3,5.1,3.6,21.5,71551,2.0
7,8.0,Near North Side,1.9,12.9,7.0,2.5,22.6,88669,1.0
8,9.0,Edison Park,1.1,3.3,6.5,7.4,35.3,40959,8.0
9,10.0,Norwood Park,2.0,5.4,9.0,11.5,39.5,32875,21.0
10,11.0,Jefferson Park,2.7,8.6,12.4,13.4,35.5,27751,25.0
11,12.0,Forest Glen,1.1,7.5,6.8,4.9,40.5,44164,11.0
12,13.0,North Park,3.9,13.2,9.9,14.4,39.0,26576,33.0
13,14.0,Albany Park,11.3,19.2,10.0,32.9,32.0,21323,53.0
14,15.0,Portage Park,4.1,11.6,12.6,19.3,34.0,24336,35.0
15,16.0,Irving Park,6.3,13.1,10.0,22.4,31.6,27249,34.0
16,17.0,Dunning,5.2,10.6,10.0,16.2,33.6,26282,28.0
17,18.0,Montclaire,8.1,15.3,13.8,23.5,38.6,22014,50.0
18,19.0,Belmont Cragin,10.8,18.7,14.6,37.3,37.3,15461,70.0
19,20.0,Hermosa,6.9,20.5,13.1,41.6,36.4,15089,71.0
20,21.0,Avondale,6.0,15.3,9.2,24.7,31.0,20039,42.0
21,22.0,Logan Square,3.2,16.8,8.2,14.8,26.2,31908,23.0
22,23.0,Humboldt park,14.8,33.9,17.3,35.4,38.0,13781,85.0
23,24.0,West Town,2.3,14.7,6.6,12.9,21.7,43198,10.0
24,25.0,Austin,6.3,28.6,22.6,24.4,37.9,15957,73.0
25,26.0,West Garfield Park,9.4,41.7,25.8,24.5,43.6,10934,92.0
26,27.0,East Garfield Park,8.2,42.4,19.6,21.3,43.2,12961,83.0
27,28.0,Near West Side,3.8,20.6,10.7,9.6,22.2,44689,15.0
28,29.0,North Lawndale,7.4,43.1,21.2,27.6,42.7,12034,87.0
29,30.0,South Lawndale,15.2,30.7,15.8,54.8,33.8,10402,96.0
...,...,...,...,...,...,...,...,...,...
48,49.0,Roseland,2.5,19.8,20.3,16.9,41.2,17949,52.0
49,50.0,Pullman,1.5,21.6,22.8,13.1,38.6,20588,51.0
50,51.0,South Deering,4.0,29.2,16.3,21.0,39.5,14685,65.0
51,52.0,East Side,6.8,19.2,12.1,31.9,42.8,17104,64.0
52,53.0,West Pullman,3.3,25.9,19.4,20.5,42.1,16563,62.0
53,54.0,Riverdale,5.8,56.5,34.6,27.5,51.5,8201,98.0
54,55.0,Hegewisch,3.3,17.1,9.6,19.2,42.9,22677,44.0
55,56.0,Garfield Ridge,2.6,8.8,11.3,19.3,38.1,26353,32.0
56,57.0,Archer Heights,8.5,14.1,16.5,35.9,39.2,16134,67.0
57,58.0,Brighton Park,14.4,23.6,13.9,45.1,39.3,13089,84.0
58,59.0,McKinley Park,7.2,18.7,13.4,32.9,35.6,16954,61.0
59,60.0,Bridgeport,4.5,18.9,13.7,22.2,31.3,22694,43.0
60,61.0,New City,11.9,29.0,23.0,41.5,38.9,12765,91.0
61,62.0,West Elsdon,11.1,15.6,16.7,37.0,37.7,15754,69.0
62,63.0,Gage Park,15.8,23.4,18.2,51.5,38.8,12171,93.0
63,64.0,Clearing,2.7,8.9,9.5,18.8,37.6,25113,29.0
64,65.0,West Lawn,5.8,14.9,9.6,33.6,39.6,16907,56.0
65,66.0,Chicago Lawn,7.6,27.9,17.1,31.2,40.6,13231,80.0
66,67.0,West Englewood,4.8,34.4,35.9,26.3,40.7,11317,89.0
67,68.0,Englewood,3.8,46.6,28.0,28.5,42.5,11888,94.0
68,69.0,Greater Grand Crossing,3.6,29.6,23.0,16.5,41.0,17285,66.0
69,70.0,Ashburn,4.0,10.4,11.7,17.7,36.9,23482,37.0
70,71.0,Auburn Gresham,4.0,27.6,28.3,18.5,41.9,15528,74.0
71,72.0,Beverly,0.9,5.1,8.0,3.7,40.5,39523,12.0
72,73.0,Washington Height,1.1,16.9,20.8,13.7,42.6,19713,48.0
73,74.0,Mount Greenwood,1.0,3.4,8.7,4.3,36.8,34381,16.0
74,75.0,Morgan Park,0.8,13.2,15.0,10.8,40.3,27149,30.0
75,76.0,O'Hare,3.6,15.4,7.1,10.9,30.3,25828,24.0
76,77.0,Edgewater,4.1,18.2,9.2,9.7,23.8,33385,19.0
77,NaN,CHICAGO,4.7,19.7,12.9,19.5,33.5,28202,NaN